// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   int32  `json:"age"`
	Phone string `json:"phone"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUser struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Age   *int32  `json:"age,omitempty"`
	Phone *string `json:"phone,omitempty"`
}
