package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"CRUD_API/ent"
	"CRUD_API/graph/model"
	"context"
	"strconv"
)

// Create User
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUser) (*ent.User, error) {
	user, err := r.Client.User.Create().
		SetName(input.Name).
		SetEmail(input.Email).
		SetAge(int(input.Age)).
		SetPhone(input.Phone).
		Save(ctx)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUser) (*ent.User, error) {
	userid, _ := strconv.Atoi(id)
	update := r.Client.User.UpdateOneID(userid)
	if input.Name != nil {
		update = update.SetName(*input.Name)
	}
	if input.Email != nil {
		update = update.SetEmail(*input.Email)
	}
	if input.Age != nil {
		update = update.SetAge(int(*input.Age))
	}
	if input.Phone != nil {
		update = update.SetPhone(*input.Phone)
	}
	return update.Save(ctx)
}

// Delete user
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	deleteId, _ := strconv.Atoi(id)
	err := r.Client.User.DeleteOneID(deleteId).Exec(ctx)
	return true, err
}

// All Users
func (r *queryResolver) Users(ctx context.Context) ([]*ent.User, error) {
	return r.Client.User.Query().All(ctx)
}

// UserID
func (r *queryResolver) UserID(ctx context.Context, id string) (*ent.User, error) {
	newid, _ := strconv.Atoi(id)
	user, _ := r.Client.User.Get(ctx, newid)
	return user, nil
}

// Age is the resolver for the age field.
func (r *userResolver) Age(ctx context.Context, obj *ent.User) (int32, error) {
	return int32(obj.Age), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *ent.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02 3:04:05 Monday"), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
